version: '3'

services:
  smt-server:
    build: .
    restart: always
    environment:
      PORT: 8102
    expose:
      - 8102
    ports:
      - 8102:8102
    logging:
      driver: journald
    volumes:
      - .:/app
    container_name: smt-server
    network_mode: bridge

  smt-server-nginx-front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - 8100
    ports:
      - 8100:8100
    restart: always
    logging:
      driver: journald
    depends_on:
     - smt-server
    container_name: smt-server-nginx-front
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.smt-server-nginx-front-redirect-web-secure.redirectscheme.scheme=https
      - traefik.http.routers.smt-server-nginx-front-web.middlewares=smt-server-nginx-front-redirect-web-secure
      - traefik.http.routers.smt-server-nginx-front-web.rule=Host(`smt.stellarium-web.org`)
      - traefik.http.routers.smt-server-nginx-front-web.entrypoints=web
      - traefik.http.routers.smt-server-nginx-front-websecure.rule=Host(`smt.stellarium-web.org`)
      - traefik.http.routers.smt-server-nginx-front-websecure.entrypoints=websecure
      - traefik.http.routers.smt-server-nginx-front-websecure.tls.certresolver=myresolver
      - traefik.http.services.smt-server-nginx-front-websecure.loadbalancer.server.port=8100
    network_mode: bridge

  smt-server-apache-front:
    build:
      context: ./apache-frontend
      dockerfile: Dockerfile
    ports:
      - 80
    restart: always
    logging:
      driver: journald
    depends_on:
     - smt-server
    container_name: smt-server-apache-front
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.smt-server-apache-front-redirect-web-secure.redirectscheme.scheme=https
      - traefik.http.routers.smt-server-apache-front-web.middlewares=smt-server-apache-front-redirect-web-secure
      - traefik.http.routers.smt-server-apache-front-web.rule=Host(`smtcas.stellarium-web.org`)
      - traefik.http.routers.smt-server-apache-front-web.entrypoints=web
      - traefik.http.routers.smt-server-apache-front-websecure.rule=Host(`smtcas.stellarium-web.org`)
      - traefik.http.routers.smt-server-apache-front-websecure.entrypoints=websecure
      - traefik.http.routers.smt-server-apache-front-websecure.tls.certresolver=myresolver
      - traefik.http.services.smt-server-apache-front-websecure.loadbalancer.server.port=80
    network_mode: bridge
