version: '3'

services:
  smt-server:
    build: .
    restart: always
    environment:
      PORT: 8102
    expose:
      - 8102
    ports:
      - 8102:8102
    logging:
      driver: journald
    volumes:
      - .:/app
    container_name: smt-server
    network_mode: bridge

  smt-server-nginx-front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - 8100
    ports:
      - 8100:8100
    restart: always
    logging:
      driver: journald
    depends_on:
     - smt-server
    container_name: smt-server-nginx-front
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.smt-server-nginx-front.rule=Host(`smt.stellarium-web.org`)"
      - "traefik.http.routers.smt-server-nginx-front.entrypoints=websecure"
      - "traefik.http.routers.smt-server-nginx-front.tls.certresolver=myresolver"
      - "traefik.http.services.smt-server-nginx-front.loadbalancer.server.port=8100"
    network_mode: bridge
